[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["echo 'Using Nixpacks Python support'"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python3 quilt_api.py & python3 quilt_github_app.py"
